baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Boilermaker 3'
primary: true
siteGroup: 09d61ba7-f8dd-4e73-bc8f-d580cffbcc1e # Boilermaker 3
sortOrder: 1
