columnSuffix: null
handle: ctaStyleAdjustments
instructions: null
name: 'CTA Style Adjustments'
searchable: false
settings:
  createButtonLabel: 'Adjust Style'
  entryTypes:
    - 03773267-1517-45c4-9a3e-c92f4340a1b2 # Style Adjustment - CTA
  includeTableView: false
  maxEntries: 6
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
